
ipx::infer_bus_interface {sCMD_tready sCMD_tvalid sCMD_tdata} xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {mRSP_tready mRSP_tvalid mRSP_tdata} xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]

ipx::infer_bus_interface {s1A_tready s1A_tvalid s1A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s1B_tready s1B_tvalid s1B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m1C_tready m1C_tvalid m1C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s1C_tready s1C_tvalid s1C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m1A_tready m1A_tvalid m1A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m1B_tready m1B_tvalid m1B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]

ipx::infer_bus_interface {s2A_tready s2A_tvalid s2A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s2B_tready s2B_tvalid s2B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m2C_tready m2C_tvalid m2C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s2C_tready s2C_tvalid s2C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m2A_tready m2A_tvalid m2A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m2B_tready m2B_tvalid m2B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]

ipx::infer_bus_interface {s3A_tready s3A_tvalid s3A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s3B_tready s3B_tvalid s3B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m3C_tready m3C_tvalid m3C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s3C_tready s3C_tvalid s3C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m3A_tready m3A_tvalid m3A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m3B_tready m3B_tvalid m3B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]

ipx::infer_bus_interface {s4A_tready s4A_tvalid s4A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s4B_tready s4B_tvalid s4B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m4C_tready m4C_tvalid m4C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s4C_tready s4C_tvalid s4C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m4A_tready m4A_tvalid m4A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m4B_tready m4B_tvalid m4B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]

ipx::infer_bus_interface {s5A_tready s5A_tvalid s5A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s5B_tready s5B_tvalid s5B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m5C_tready m5C_tvalid m5C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s5C_tready s5C_tvalid s5C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m5A_tready m5A_tvalid m5A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m5B_tready m5B_tvalid m5B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]

ipx::infer_bus_interface {s6A_tready s6A_tvalid s6A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s6B_tready s6B_tvalid s6B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m6C_tready m6C_tvalid m6C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s6C_tready s6C_tvalid s6C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m6A_tready m6A_tvalid m6A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m6B_tready m6B_tvalid m6B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]

ipx::infer_bus_interface {s7A_tready s7A_tvalid s7A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s7B_tready s7B_tvalid s7B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m7C_tready m7C_tvalid m7C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s7C_tready s7C_tvalid s7C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m7A_tready m7A_tvalid m7A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m7B_tready m7B_tvalid m7B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]

ipx::infer_bus_interface {s8A_tready s8A_tvalid s8A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s8B_tready s8B_tvalid s8B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m8C_tready m8C_tvalid m8C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {s8C_tready s8C_tvalid s8C_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m8A_tready m8A_tvalid m8A_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {m8B_tready m8B_tvalid m8B_tdata   } xilinx.com:interface:axis_rtl:1.0 [ipx::current_core]

set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces s1A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces s1B -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces m1C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces s1C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces m1A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces m1B -of_objects [ipx::current_core]]

set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces s2A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces s2B -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces m2C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces s2C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces m2A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces m2B -of_objects [ipx::current_core]]

set_property enablement_dependency {($NUM_ACCs >= 3)} [ipx::get_bus_interfaces s3A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 3)} [ipx::get_bus_interfaces s3B -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 3)} [ipx::get_bus_interfaces m3C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 3)} [ipx::get_bus_interfaces s3C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 3)} [ipx::get_bus_interfaces m3A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 3)} [ipx::get_bus_interfaces m3B -of_objects [ipx::current_core]]

set_property enablement_dependency {($NUM_ACCs >= 4)} [ipx::get_bus_interfaces s4A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 4)} [ipx::get_bus_interfaces s4B -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 4)} [ipx::get_bus_interfaces m4C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 4)} [ipx::get_bus_interfaces s4C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 4)} [ipx::get_bus_interfaces m4A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 4)} [ipx::get_bus_interfaces m4B -of_objects [ipx::current_core]]

set_property enablement_dependency {($NUM_ACCs >= 5)} [ipx::get_bus_interfaces s5A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 5)} [ipx::get_bus_interfaces s5B -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 5)} [ipx::get_bus_interfaces m5C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 5)} [ipx::get_bus_interfaces s5C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 5)} [ipx::get_bus_interfaces m5A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 5)} [ipx::get_bus_interfaces m5B -of_objects [ipx::current_core]]

set_property enablement_dependency {($NUM_ACCs >= 6)} [ipx::get_bus_interfaces s6A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 6)} [ipx::get_bus_interfaces s6B -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 6)} [ipx::get_bus_interfaces m6C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 6)} [ipx::get_bus_interfaces s6C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 6)} [ipx::get_bus_interfaces m6A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 6)} [ipx::get_bus_interfaces m6B -of_objects [ipx::current_core]]

set_property enablement_dependency {($NUM_ACCs >= 7)} [ipx::get_bus_interfaces s7A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 7)} [ipx::get_bus_interfaces s7B -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 7)} [ipx::get_bus_interfaces m7C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 7)} [ipx::get_bus_interfaces s7C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 7)} [ipx::get_bus_interfaces m7A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 7)} [ipx::get_bus_interfaces m7B -of_objects [ipx::current_core]]

set_property enablement_dependency {($NUM_ACCs >= 8)} [ipx::get_bus_interfaces s8A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 8)} [ipx::get_bus_interfaces s8B -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 8)} [ipx::get_bus_interfaces m8C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 8)} [ipx::get_bus_interfaces s8C -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 8)} [ipx::get_bus_interfaces m8A -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 8)} [ipx::get_bus_interfaces m8B -of_objects [ipx::current_core]]

# sCMD:mRSP:s1A:s1B:m1C:s1C:m1A:m1B:s2A:s2B:m2C:s2C:m2A:m2B:s3A:s3B:m3C:s3C:m3A:m3B:s4A:s4B:m4C:s4C:m4A:m4B:s5A:s5B:m5C:s5C:m5A:m5B:s6A:s6B:m6C:s6C:m6A:m6B:s7A:s7B:m7C:s7C:m7A:m7B:s8A:s8B:m8C:s8C:m8A:m8B
set_property value sCMD:mRSP:s1A:s1B:m1C:s1C:m1A:m1B:s2A:s2B:m2C:s2C:m2A:m2B:s3A:s3B:m3C:s3C:m3A:m3B:s4A:s4B:m4C:s4C:m4A:m4B:s5A:s5B:m5C:s5C:m5A:m5B:s6A:s6B:m6C:s6C:m6A:m6B:s7A:s7B:m7C:s7C:m7A:m7B:s8A:s8B:m8C:s8C:m8A:m8B [ipx::get_bus_parameters ASSOCIATED_BUSIF -of_objects [ipx::get_bus_interfaces ACLK -of_objects [ipx::current_core]]]


ipx::infer_bus_interface {ap1_done ap1_idle ap1_ready ap1_start} xilinx.com:interface:acc_handshake_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {ap2_done ap2_idle ap2_ready ap2_start} xilinx.com:interface:acc_handshake_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {ap3_done ap3_idle ap3_ready ap3_start} xilinx.com:interface:acc_handshake_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {ap4_done ap4_idle ap4_ready ap4_start} xilinx.com:interface:acc_handshake_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {ap5_done ap5_idle ap5_ready ap5_start} xilinx.com:interface:acc_handshake_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {ap6_done ap6_idle ap6_ready ap6_start} xilinx.com:interface:acc_handshake_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {ap7_done ap7_idle ap7_ready ap7_start} xilinx.com:interface:acc_handshake_rtl:1.0 [ipx::current_core]
ipx::infer_bus_interface {ap8_done ap8_idle ap8_ready ap8_start} xilinx.com:interface:acc_handshake_rtl:1.0 [ipx::current_core]

set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces ap1 -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_bus_interfaces ap2 -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 3)} [ipx::get_bus_interfaces ap3 -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 4)} [ipx::get_bus_interfaces ap4 -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 5)} [ipx::get_bus_interfaces ap5 -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 6)} [ipx::get_bus_interfaces ap6 -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 7)} [ipx::get_bus_interfaces ap7 -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 8)} [ipx::get_bus_interfaces ap8 -of_objects [ipx::current_core]]

set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_ports ap1_arg1_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_ports ap1_arg2_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_ports ap1_arg3_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_ports ap2_arg1_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_ports ap2_arg2_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 2)} [ipx::get_ports ap2_arg3_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 3)} [ipx::get_ports ap3_arg1_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 3)} [ipx::get_ports ap3_arg2_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 3)} [ipx::get_ports ap3_arg3_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 4)} [ipx::get_ports ap4_arg1_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 4)} [ipx::get_ports ap4_arg2_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 4)} [ipx::get_ports ap4_arg3_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 5)} [ipx::get_ports ap5_arg1_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 5)} [ipx::get_ports ap5_arg2_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 5)} [ipx::get_ports ap5_arg3_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 6)} [ipx::get_ports ap6_arg1_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 6)} [ipx::get_ports ap6_arg2_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 6)} [ipx::get_ports ap6_arg3_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 7)} [ipx::get_ports ap7_arg1_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 7)} [ipx::get_ports ap7_arg2_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 7)} [ipx::get_ports ap7_arg3_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 8)} [ipx::get_ports ap8_arg1_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 8)} [ipx::get_ports ap8_arg2_V -of_objects [ipx::current_core]]
set_property enablement_dependency {($NUM_ACCs >= 8)} [ipx::get_ports ap8_arg3_V -of_objects [ipx::current_core]]
